name: babatv-channels
base: core22
version: '1.0'
summary: Program streaming TV channels
description: |
  A simple Python app to stream live TV channels using mpv and tkinter.

grade: stable
confinement: strict              

architectures:
  - arm64

apps:
  babatv:
    command: bin/babatv
    icon: meta/gui/Baba-TV-icon.png
    desktop: gui/babatv.desktop
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
      LD_LIBRARY_PATH: $SNAP/usr/lib:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH
      MPLBACKEND: TkAgg
    plugs:
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl
      - audio-playback

parts:
  babatv:
    plugin: python
    source: https://github.com/babamanstudios/TV-channels.git
    python-packages:
      - yt-dlp   # or yt-dlp if you use it
    stage-packages:
      - mpv
      - libmpv1
      - python3-tk
      - tcl
      - tk
    override-build: |
      sed -i '1i#!/usr/bin/env python3' main.py
      chmod +x main.py
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cat <<EOF > $SNAPCRAFT_PART_INSTALL/bin/babatv
      #!/bin/sh
      exec python3 "$SNAP/main.py"
      EOF
      chmod +x $SNAPCRAFT_PART_INSTALL/bin/babatv
